In [1]:
import numpy as np

### 1. Searching

In [17]:
arr = np.array([1,3,4,6,5,7,12,13])

# Linear Search
index = np.where(arr == 3)[0]
print(index)

# Binary Search
index = np.searchsorted(arr, 3)
print(index)

# Searching Closest Value
index = np.argmin(abs(arr - 11))
print(index)

[1]
1
6


### 2. Sorting

In [21]:
arr = np.array([5,7,9,0,3,1,6,2,4,8])

# Quick Sort
sorted_arr = np.sort(arr)
print(sorted_arr)

# Quick Sort
sorted_arr = np.sort(arr, kind = 'quicksort')
print(sorted_arr)

# Heap Sort
sorted_arr = np.sort(arr, kind = 'heapsort')
print(sorted_arr)

# Merge Sort
sorted_arr = np.sort(arr, kind = 'mergesort')
print(sorted_arr)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
