In [2]:
import numpy as np

### 1. Converting Data Structures to Numpy Array

##### 1.1) Converting a tuple to an array

In [7]:
tpl = (1,2,3)
print(tpl)
print(type(tpl))
print('-'*10)

arr = np.array(tpl)
print(arr)
print(type(arr))

(1, 2, 3)
<class 'tuple'>
----------
[1 2 3]
<class 'numpy.ndarray'>


##### 1.2) Converting a list to an array

In [6]:
lst = [1,2,3]
print(lst)
print(type(lst))
print('-'*10)

arr = np.array(lst)
print(arr)
print(type(arr))

[1, 2, 3]
<class 'list'>
----------
[1 2 3]
<class 'numpy.ndarray'>


##### 1.3) Converting a dictionary to an array

In [15]:
dct = {1 : 'apple', 2 : 'banana', 3 : 'cherry'}
print(dct)
print(type(dct))
print('-'*10)

arr = np.array(dct)
print(arr)
print(type(arr))
print('-'*10)

arr_k = np.array(list(dct.keys()))
arr_v = np.array(list(dct.values()))
print(arr_k)
print(type(arr_k))
print(arr_v)
print(type(arr_v))

{1: 'apple', 2: 'banana', 3: 'cherry'}
<class 'dict'>
----------
{1: 'apple', 2: 'banana', 3: 'cherry'}
<class 'numpy.ndarray'>
----------
[1 2 3]
<class 'numpy.ndarray'>
['apple' 'banana' 'cherry']
<class 'numpy.ndarray'>


##### 1.4) Converting a set to an array

In [18]:
set_ = {1,2,3}
print(set_)
print(type(set_))
print('-'*10)

arr = np.array(list(set_))
print(arr)
print(type(arr))

{1, 2, 3}
<class 'set'>
----------
[1 2 3]
<class 'numpy.ndarray'>


##### 1.5) Converting String to Array

In [21]:
arr = np.array('hello world')
print(arr)
print(type(arr))

hello world
<class 'numpy.ndarray'>


### 2. Convering the Datatype of Numpy Array

##### 2.1) Create an array of integers

In [27]:
arr = np.array([1,2,3,4,5])
print(arr)
arr_ = arr.astype('float')
print(arr_)

arr_ = arr.astype('str')
print(arr_)

arr_ = arr.astype('bool')
print(arr_)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]
['1' '2' '3' '4' '5']
[ True  True  True  True  True]


##### 2.2) Create an array of floats

In [31]:
arr = np.array([1.,2.,3.,4.,5.])
print(arr)

arr_ = arr.astype('int')
print(arr_)

arr_ = arr.astype('str')
print(arr_)

arr_ = arr.astype('bool')
print(arr_)

[1. 2. 3. 4. 5.]
[1 2 3 4 5]
['1.0' '2.0' '3.0' '4.0' '5.0']
[ True  True  True  True  True]


##### 2.3) Create an array of strings

In [44]:
arr = np.array(['1','2','3','4','5'])
print(arr)

arr_ = arr.astype('int')
print(arr_)

arr_ = arr.astype('float')
print(arr_)

arr_ = arr.astype('bool')
print(arr_)

['1' '2' '3' '4' '5']
[1 2 3 4 5]
[1. 2. 3. 4. 5.]
[ True  True  True  True  True]


##### 2.4) Create an array of boolean

In [47]:
arr = np.array([True, False, False, False, True])
print(arr)

arr_ = arr.astype('int')
print(arr_)

arr_ = arr.astype('float')
print(arr_)

arr_ = arr.astype('str')
print(arr_)

[ True False False False  True]
[1 0 0 0 1]
[1. 0. 0. 0. 1.]
['True' 'False' 'False' 'False' 'True']
