In [1]:
import numpy as np

### 1. Arithmetic

In [ ]:
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3],[4,5,6]])

print(a)
print(b)
print('-'*10)

# Addition
print(a + 2)
print(a + b)
print('-'*10)


# Subtract
print(a - 2)
print(a - b)
print('-'*10)

# Multiplication
print(a * 2)
print(a * b)
print('-'*10)

# Division
print(a / 2)
print(a / b)
print('-'*10)

# Exponential
print(a ** 2)
print(a ** b)
print('-'*10)

# Modulo
print(a % 2)
print(a % b)
print('-'*10)

### 2. Comparison

In [ ]:
a = np.array([1,2,3])
b = np.array([[1, 2, 3],[4,5,6]])

print(a)
print(b)
print('-'*10)

# >
print(a > b)
print('-'*10)

# <
print(a < b)
print('-'*10)

# >=
print(a >= b)
print('-'*10)

# <=
print(a <= b)
print('-'*10)

# ==
print(a == b)
print('-'*10)

# !=
print(a != b)

### 3. Logical

In [180]:
a = np.array([1,2,3])
b = np.array([[1, 2, 3],[4,5,6]])
print(a)
print(b)

print('-'*10)

print(a & b)
print('-'*10)

print(a | b)
print('-'*10)

print(a ^ b)
print('-'*10)

[1 2 3]
[[1 2 3]
 [4 5 6]]
----------
[[1 2 3]
 [0 0 2]]
----------
[[1 2 3]
 [5 7 7]]
----------
[[0 0 0]
 [5 7 5]]
----------


### 4. bitwise

In [3]:
a = np.array([1,2,3])
b = np.array([[1, 2, 3],[4,5,6]])

print(a)
print(b)
print('-'*10)

print(np.bitwise_and(a,b))

print(np.bitwise_or(a,b))

print(np.bitwise_xor(a,b))

print(np.bitwise_not(a,b))

print(np.right_shift(a,b))

print(np.left_shift(a,b))

[1 2 3]
[[1 2 3]
 [4 5 6]]
----------
[[1 2 3]
 [0 0 2]]
[[1 2 3]
 [5 7 7]]
[[0 0 0]
 [5 7 5]]
[[-2 -3 -4]
 [-2 -3 -4]]
[[0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]]
