In [1]:
import numpy as np

### 1d array

In [11]:
np.random.seed(10)
arr = np.random.randint(1,11,size = 10)

print(arr)
print('-'*10)

indices = np.where(arr >= 5)
print(list(indices[0]))
print('-'*10)

print(arr[indices])

[10  5  1  2 10  1  2  9 10  1]
----------
[0, 1, 4, 7, 8]
----------
[10  5 10  9 10]


### 2d array

In [15]:
np.random.seed(10)
arr = np.random.randint(1,11,size = (3,3))

print(arr)
print('-'*10)

indices = np.where(arr >= 5)
print(indices)
print('-'*10)

print(arr[indices])

[[10  5  1]
 [ 2 10  1]
 [ 2  9 10]]
----------
(array([0, 0, 1, 2, 2]), array([0, 1, 1, 1, 2]))
----------
[10  5 10  9 10]


### 3d array

In [18]:
np.random.seed(10)
arr = np.random.randint(1,11,size = (3,3,3))

print(arr)
print('-'*10)

indices = np.where(arr >= 5)
print(indices)
print('-'*10)

print(arr[indices])

[[[10  5  1]
  [ 2 10  1]
  [ 2  9 10]]

 [[ 1  9  7]
  [ 5  4  1]
  [ 5  7  9]]

 [[ 2  9  5]
  [ 2  4  7]
  [ 6  4 10]]]
----------
(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2]), array([0, 0, 1, 2, 2, 0, 0, 1, 2, 2, 2, 0, 0, 1, 2, 2]), array([0, 1, 1, 1, 2, 1, 2, 0, 0, 1, 2, 1, 2, 2, 0, 2]))
----------
[10  5 10  9 10  9  7  5  5  7  9  9  5  7  6 10]


In [23]:
for i in range(len(indices)):
  print(indices[i])


[0 0 0 0 0 1 1 1 1 1 1 2 2 2 2 2]
[0 0 1 2 2 0 0 1 2 2 2 0 0 1 2 2]
[0 1 1 1 2 1 2 0 0 1 2 1 2 2 0 2]
