In [4]:
import numpy as np

arr = np.random.randint(1,11,size=(5,5))
arr

array([[ 1,  9,  8,  5,  1],
       [ 7,  8,  2,  4,  9],
       [ 2,  4,  7,  5,  6],
       [ 9, 10,  9,  5,  5],
       [ 7,  4,  1,  8,  4]])

### 1. Filtering

##### 1.1) Filter elements greater than 5

In [7]:
arr[arr>5]

array([ 9,  8,  7,  8,  9,  7,  6,  9, 10,  9,  7,  8])

##### 1.2) Filter the elements that are even

In [12]:
arr[arr%2 == 0]

array([ 8,  8,  2,  4,  2,  4,  6, 10,  4,  8,  4])

##### 1.3) Filter elements that are both greather than 5 and even

In [19]:
arr[(arr>5) & (arr%2 == 0)]

array([ 8,  8,  6, 10,  8])

##### 1.4) Filter elements that are divisible by either 3 or 7

In [21]:
arr[(arr % 3 == 0) | (arr % 7 == 0)]

array([9, 7, 9, 7, 6, 9, 9, 7])

##### 1.5) Filter elements that based on condition on another array

In [26]:
 arr1 = np.array([True, False, True,False,True])

 arr[arr1]

array([[1, 9, 8, 5, 1],
       [2, 4, 7, 5, 6],
       [7, 4, 1, 8, 4]])

##### 1.6 Filter the elements based on condition of specific row

In [40]:
filtered_arr = arr[2][arr[2,:] > 5]

filtered_arr

array([7, 6])

### 2. Aggregate Functions

##### 2.1) sum

In [47]:
arr = np.array([1,2,3,4,5])
print(np.sum(arr))

arr = np.array([[1,2,3],[4,5,6]])
print(np.sum(arr))
print(np.sum(arr, axis = 0))
print(np.sum(arr, axis = 1))

15
21
[5 7 9]
[ 6 15]


##### 2.2) mean

In [49]:
arr = np.array([1,2,3,4,5])
print(np.mean(arr))

arr = np.array([[1,2,3],[4,5,6]])
print(np.mean(arr))
print(np.mean(arr, axis = 0))
print(np.mean(arr, axis = 1))

3.0
3.5
[2.5 3.5 4.5]
[2. 5.]


##### 2.3) standard daviation

In [51]:
arr = np.array([1,2,3,4,5])
print(np.std(arr))

arr = np.array([[1,2,3],[4,5,6]])
print(np.std(arr))
print(np.std(arr, axis = 0))
print(np.std(arr, axis = 1))

1.4142135623730951
1.707825127659933
[1.5 1.5 1.5]
[0.81649658 0.81649658]


##### 2.4) min-max

In [54]:
arr = np.array([1,2,3,4,5])
print(np.min(arr))

arr = np.array([[1,2,3],[4,5,6]])
print(np.min(arr))
print(np.min(arr, axis = 0))
print(np.min(arr, axis = 1))

print('-'*20)

arr = np.array([1,2,3,4,5])
print(np.max(arr))

arr = np.array([[1,2,3],[4,5,6]])
print(np.max(arr))
print(np.max(arr, axis = 0))
print(np.max(arr, axis = 1))

1
1
[1 2 3]
[1 4]
--------------------
5
6
[4 5 6]
[3 6]
