In [1]:
import numpy as np

### 1. Generating Random Numbers

In [13]:
print(np.random.rand())
print(np.random.rand(3))

print(np.random.randint(10))
print(np.random.randint(10, size=(3, 5)))

0.045962546686202144
[0.93922746 0.83334219 0.34285859]
5
[[6 4 0 8 2]
 [4 3 1 2 8]
 [4 9 1 6 6]]


### 2. Random Numbers with Seed

In [15]:
np.random.seed(2)

print(np.random.rand())
print(np.random.rand(3))

print(np.random.randint(10))
print(np.random.randint(10, size=(3, 5)))

0.43599490214200376
[0.02592623 0.54966248 0.43532239]
8
[[7 2 1 5 4]
 [4 5 7 3 6]
 [4 3 7 6 1]]


In [17]:
np.random.seed(5)

print(np.random.rand())
print(np.random.rand(3))

print(np.random.randint(10))
print(np.random.randint(10, size=(3, 5)))

0.22199317108973948
[0.87073231 0.20671916 0.91861091]
8
[[4 7 0 0 7]
 [1 5 7 0 1]
 [4 6 2 9 9]]


In [18]:
np.random.seed(5)

print(np.random.rand())
print(np.random.rand(3))

print(np.random.randint(10))
print(np.random.randint(10, size=(3, 5)))

0.22199317108973948
[0.87073231 0.20671916 0.91861091]
8
[[4 7 0 0 7]
 [1 5 7 0 1]
 [4 6 2 9 9]]


In [24]:
np.random.seed(5)

print(np.random.rand())
print(np.random.rand(3))

print(np.random.randint(10))
print(np.random.randint(10, size=(3, 5)))

0.22199317108973948
[0.87073231 0.20671916 0.91861091]
8
[[4 7 0 0 7]
 [1 5 7 0 1]
 [4 6 2 9 9]]


### 3. Seed in Loops

In [57]:
np.random.seed(5)

for i in range(10):
  arr = np.random.randint(2, size = 1000)
  print(len(arr[arr == 1]) , len(arr[arr == 0]))

505 495
509 491
481 519
508 492
510 490
490 510
503 497
475 525
496 504
499 501
