In [22]:
import numpy as np

### 1. Masking with Boolean Arrays

In [27]:
arr = np.array([1,2,np.nan,4,5,np.nan])

print(np.isnan(arr))
print(arr[np.isnan(arr)])
print(arr[~np.isnan(arr)])

[False False  True False False  True]
[nan nan]
[1. 2. 4. 5.]


### 2. Replacing outliers with s specific value

In [29]:
arr = np.array([1,2,3,4,5,6,7,8,9])

arr[arr > 7] = 7
arr[arr < 3] = 3
print(arr)

[3 3 3 4 5 6 7 7 7]


### 3. Removing the Duplicates

In [31]:
arr = np.array([1,2,2,2,3,3,4,5,6,7,8,9])
print(arr)

unique_arr = np.unique(arr)
print(unique_arr)

print(set(arr))

[1 2 2 2 3 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
{1, 2, 3, 4, 5, 6, 7, 8, 9}


### 4. Categorical data to One Hot Encoding

In [35]:
categorical_arr = np.array(['A','B','C','D','E'])

numrical_arr = np.array([0,1,2,3,4])

print(categorical_arr)

one_hot_arr = np.eye(5)[numrical_arr]
print(one_hot_arr)

['A' 'B' 'C' 'D' 'E']
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### 5. Data Normalization

In [43]:
 arr = np.array([10000,200000,300000,4000000,5000000])

 normalized_arr = (arr - arr.min()) / (arr.max() - arr.min())
 print(normalized_arr)

[0.         0.03807615 0.05811623 0.7995992  1.        ]
