In [7]:
import numpy as np

### 1. Determinant

In [14]:
A = np.array([[1,2],[3,4]])
determinant = np.linalg.det(A)
determinant

-2.0000000000000004

In [15]:
B = np.array([[1,2,3], [4,5,6], [7,8,9]])
determinant = np.linalg.det(B)
determinant

0.0

### 2. Transpose

In [16]:
Transpose = np.transpose(B)
Transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [17]:
C = np.array([[1,2,3],[4,5,6]])
Transpose = np.transpose(C)
Transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

### 3. Inverse

In [18]:
A = np.array([[1,2],[3,4]])
Inverse = np.linalg.inv(A)
Inverse

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [19]:
B = np.array([[1,2,3], [4,5,6]])
Inverse = np.linalg.inv(B)
Inverse

LinAlgError: Last 2 dimensions of the array must be square