In [3]:
import numpy as np

### 1. Arrays vs Lists Comparison

In [ ]:
lst = [1,3,2]
print(lst)
print(type(lst))
print('---')

arr = np.array([1,2,3])
print(arr)
print(type(arr))
print('---')

print(arr == lst)
print(arr.tolist() == lst)

print(sorted(arr) == sorted(lst))

### 2. Adding elements in an Array vs List

In [18]:
lst = [1,3,2]
arr = np.array([1,2,3])

print(lst)
lst.append(4)
print(lst)
print('---')

print(arr)
arr = np.append(arr, 4)
print(arr)

[1, 3, 2]
[1, 3, 2, 4]
---
[1 2 3]
[1 2 3 4]


### 3. Removing elements in an Array vs List

In [25]:
lst = [1,3,2]
arr = np.array([1,2,3])

print(lst)
del lst[-2]
print(lst)
print('---')

print(arr)
arr = np.delete(arr,-2)
print(arr)

[1, 3, 2]
[1, 2]
---
[1 2 3]
[1 3]


### 4. Updating elements in an Arrays vs List

In [31]:
lst = [1,3,2]
print(lst)
lst[-2] = 2
lst[-1] = 3
print(lst)
print('---')

arr = np.array([1,3,2])
print(arr)
arr[-2] = 2
arr[-1] = 3
print(arr)

[1, 3, 2]
[1, 2, 3]
---
[1 3 2]
[1 2 3]


### 5. Array vs List Comparison

In [45]:
import time

# Creating the data
my_list = list(range(10000000))
my_array = np.arange(10000000)

# Search time for list
start_time = time.time()
for _ in range(100):
  if 5000000 in my_list:
    pass
end_time = time.time()
print('List : ', end_time - start_time)


# Search time for Array
start_time = time.time()
for _ in range(100):
  if 5000000 in my_array:
    pass
end_time = time.time()
print('Array : ', end_time - start_time)

List :  5.364999294281006
Array :  0.9616692066192627
