In [7]:
import numpy as np

### 1. Dot product

In [8]:
a = np.array([1,2])
b= np.array ([2,3])
dot_product = np.dot(a,b)
dot_product

8

In [9]:
c = np.array([1,2,3])
d = np.array([2,3,4])
dot_product = np.dot(c,d)
dot_product

20

In [10]:
x = np.array([1,2])
y = np.array([5,3])
dot_product = np.dot(x,y)
dot_product

11

### 2. Matrix Multiplication

In [11]:
A = np.array([[1,2],[3,4]])
B= np.array([[2,3],[4,5]])
product = np.matmul(A,B)
product

array([[10, 13],
       [22, 29]])

In [12]:
C = np.array([1,2])
D = np.array([[4,1],[3,5]])
product = np.matmul(C,D)
product

array([10, 11])

### 3. Dot Product

In [13]:
A = np.array([[1,2],[3,4]])
B= np.array([[2,3],[4,5]])
product = np.dot(A,B)
product

array([[10, 13],
       [22, 29]])