In [140]:
import numpy as np

### 1. Zeros

In [141]:
zeros_array = np.zeros(10)
print(zeros_array)
print('-----')

zeros_array = np.zeros((2, 4))
print(zeros_array)
print('-----')

zeros_array = np.zeros((2, 3, 4))
print(zeros_array)
print('-----')

zeros_array = np.zeros((2, 3), dtype = int)
print(zeros_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
-----
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
-----
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
-----
[[0 0 0]
 [0 0 0]]


### 2. Ones

In [142]:
ones_array = np.ones(10)
print(ones_array)
print('-----')

ones_array = np.ones((2, 4))
print(ones_array)
print('-----')

ones_array = np.ones((2, 3, 4))
print(ones_array)
print('-----')

ones_array = np.ones((2, 3), dtype = int)
print(ones_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
-----
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
-----
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
-----
[[1 1 1]
 [1 1 1]]


### 3. Eye

In [143]:
eye_array = np.eye(3)
print(eye_array)
print('-----')

eye_array = np.eye(3, 4)
print(eye_array)
print('-----')

eye_array = np.eye(3, 4, dtype = int)
print(eye_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
-----
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
-----
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


 ### 4. Random Number Generation

In [144]:
print(np.random.rand())
print(np.random.rand(10))
print(np.random.rand(3, 3))

print(np.random.randint(100))
print(np.random.randint(100, size=10))
print(np.random.randint(100, size=(3, 3)))
print(np.random.randint(low=100, high=200, size=(3, 3)))

# Generate a random number from a normal distribution with mean 0 and standard deviation 1
print(np.random.randn())

# Generate a 2D array of 3x3 random numbers from a uniform distribution between 0 and 1
print(np.random.uniform(size=(3, 3)))

# Generate a 2D array of 3x3 random numbers from a binomial distribution with n=10 and p=0.5
print(np.random.binomial(10, 0.5, size=(3, 3)))

# Poisson ,Exponential, Gamma, Chi-squared, T-distribution, F-distribution Beta Log-normal Laplace

0.7338305664313527
[0.91581302 0.99275679 0.00570013 0.38339361 0.07665591 0.34215239
 0.38454908 0.70341512 0.62588359 0.86636757]
[[0.27616757 0.53582686 0.49108533]
 [0.20538545 0.18673001 0.80832864]
 [0.83919948 0.62655159 0.65940628]]
97
[76 59 97  7 27 23 62 18 64 24]
[[30 36 30]
 [31 43 86]
 [60 55 22]]
[[171 119 133]
 [179 109 184]
 [161 159 180]]
-0.0596788432095212
[[0.13292975 0.18059088 0.28364867]
 [0.7254095  0.78564065 0.21566929]
 [0.26057121 0.21164359 0.77006823]]
[[3 5 4]
 [2 6 6]
 [4 7 8]]
