In [1]:
import numpy as np

### 1. Creating Multi-dimensional Arrays

##### 1.1) Create a 2D array from a list of lists

In [4]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


##### 1.2) Create a 3D array from a list of lists

In [5]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],
                [[1,2,3],[4,5,6],[7,8,9]],
                [[1,2,3],[4,5,6],[7,8,9]]])
print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


##### 1.3) Create a 2D array from a list of tuples

In [6]:
arr = np.array([(1,2,3),(4,5,6)])
print(arr)

[[1 2 3]
 [4 5 6]]


##### 1.4) Create a 2D array from a list of arrays

In [10]:
arr = np.array([np.array([1,2,3]), np.array([4,5,6])])
print(arr)

[[1 2 3]
 [4 5 6]]


##### 1.5) Create a 2D array from a list of strings

In [11]:
arr = np.array([['1','2','3'],['4','5','6']])
print(arr)

[['1' '2' '3']
 ['4' '5' '6']]


##### 1.6) Create a 2D array from a list of dictionaries

In [12]:
arr = np.array([{'a' : 1, 'b' : 2, 'c' : 3},{'d' : 4, 'e' : 5, 'f' : 6}])
print(arr)

[{'a': 1, 'b': 2, 'c': 3} {'d': 4, 'e': 5, 'f': 6}]


### 2. Finding details of an arrays

##### 2.1) Print the shape of the array

In [18]:
arr = np.array([[1,1],[4,1],[2,3]])

print(arr.shape)

(3, 2)


##### 2.2) Print the number of dimensions of the array




In [20]:
arr = np.array([[1,1],[4,1],[2,3]])

print(arr.ndim)

3


##### 2.3) Print the data type of the array

In [23]:
arr = np.array([[1,1],[4,1],[2,3]])
print(arr.dtype)

int64


##### 2.4) Print the size of the array

In [34]:
arr = np.array([[1,1,2,2],[2,3,2,1]])
print(arr.size)

8


##### 2.5) Print the item size | bytes taken by each element in an array

In [33]:
arr = np.array([[1,1,2],[1,2,3],[3,2,1]])
print(arr.itemsize)

8


##### 2.6) Print the type of the array

In [35]:
print(type(arr))

<class 'numpy.ndarray'>
